"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { NotesViewer } from "@/components/math/katex-renderer";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import { BookOpen, Play, ArrowLeft } from "lucide-react";

interface TopicDetail {
  id: string;
  name: string;
  description: string;
  strand: string;
  term: number;
  chapter: number;
  totalSkills: number;
  notesHtml: string | null;
  prerequisites: Array<{ id: string; name: string; relationship: string }>;
  skillCounts: Record<string, number>;
  totalQuestions: number;
}

export default function TopicDetailPage() {
  const { topicId } = useParams<{ topicId: string }>();
  const [topic, setTopic] = useState<TopicDetail | null>(null);

  useEffect(() => {
    fetch(`/api/curriculum/${topicId}`)
      .then((r) => r.json())
      .then(setTopic)
      .catch(console.error);
  }, [topicId]);

  if (!topic) {
    return (
      <div className="p-6">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-4xl">
      <Link
        href="/topics"
        className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="size-3" />
        Back to Topics
      </Link>

      <div>
        <div className="flex items-center gap-3 mb-2">
          <h1 className="text-2xl font-bold">{topic.name}</h1>
          <Badge variant="outline">Term {topic.term}</Badge>
          <Badge variant="outline">Ch. {topic.chapter}</Badge>
        </div>
        <p className="text-muted-foreground">{topic.description}</p>
      </div>

      {topic.prerequisites.length > 0 && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          Prerequisites:{" "}
          {topic.prerequisites.map((p) => (
            <Link
              key={p.id}
              href={`/topics/${p.id}`}
              className="underline hover:text-foreground"
            >
              {p.name}
            </Link>
          ))}
        </div>
      )}

      <div className="flex gap-3">
        <Link
          href={`/topics/${topicId}/practice`}
          className={cn(buttonVariants({ size: "lg" }), "gap-2")}
        >
          <Play className="size-4" />
          Practice ({topic.totalQuestions} questions)
        </Link>
      </div>

      <Tabs defaultValue={topic.notesHtml ? "notes" : "skills"}>
        <TabsList>
          {topic.notesHtml && (
            <TabsTrigger value="notes" className="gap-1">
              <BookOpen className="size-3" />
              Notes
            </TabsTrigger>
          )}
          <TabsTrigger value="skills">
            Skills ({topic.totalSkills})
          </TabsTrigger>
        </TabsList>

        {topic.notesHtml && (
          <TabsContent value="notes">
            <Card className="p-6">
              <NotesViewer html={topic.notesHtml} />
            </Card>
          </TabsContent>
        )}

        <TabsContent value="skills">
          <div className="grid gap-2">
            {Object.entries(topic.skillCounts).map(([skillId, count]) => (
              <Card key={skillId} className="p-3 flex justify-between items-center">
                <div>
                  <span className="text-sm font-medium">
                    {skillId.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}
                  </span>
                </div>
                <Badge variant="outline">{count} questions</Badge>
              </Card>
            ))}
            {Object.keys(topic.skillCounts).length === 0 && (
              <p className="text-sm text-muted-foreground py-4">
                No questions available yet for this topic. Questions will be
                generated by the AI.
              </p>
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
